# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/lib/transformers/batch_encoding.proto
"""Generated protocol buffer code."""
# third party
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


# syft absolute
from syft.proto.core.common import (
    common_object_pb2 as proto_dot_core_dot_common_dot_common__object__pb2,
)
from syft.proto.lib.python import dict_pb2 as proto_dot_lib_dot_python_dot_dict__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n+proto/lib/transformers/batch_encoding.proto\x12\x15syft.lib.transformers\x1a%proto/core/common/common_object.proto\x1a\x1bproto/lib/python/dict.proto"W\n\rBatchEncoding\x12!\n\x02id\x18\x01 \x01(\x0b\x32\x15.syft.core.common.UID\x12#\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x15.syft.lib.python.Dictb\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "proto.lib.transformers.batch_encoding_pb2", globals()
)
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _BATCHENCODING._serialized_start = 138
    _BATCHENCODING._serialized_end = 225
# @@protoc_insertion_point(module_scope)
