# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/core/node/common/plan/plan.proto
"""Generated protocol buffer code."""
# third party
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


# syft absolute
from syft.proto.core.node.common.action import (
    action_pb2 as proto_dot_core_dot_node_dot_common_dot_action_dot_action__pb2,
)
from syft.proto.core.pointer import (
    pointer_pb2 as proto_dot_core_dot_pointer_dot_pointer__pb2,
)

DESCRIPTOR = _descriptor.FileDescriptor(
    name="proto/core/node/common/plan/plan.proto",
    package="syft.core.node.common.plan",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n&proto/core/node/common/plan/plan.proto\x12\x1asyft.core.node.common.plan\x1a*proto/core/node/common/action/action.proto\x1a proto/core/pointer/pointer.proto"i\n\x04Plan\x12\x35\n\x07\x61\x63tions\x18\x01 \x03(\x0b\x32$.syft.core.node.common.action.Action\x12*\n\x06inputs\x18\x02 \x03(\x0b\x32\x1a.syft.core.pointer.Pointerb\x06proto3',
    dependencies=[
        proto_dot_core_dot_node_dot_common_dot_action_dot_action__pb2.DESCRIPTOR,
        proto_dot_core_dot_pointer_dot_pointer__pb2.DESCRIPTOR,
    ],
)


_PLAN = _descriptor.Descriptor(
    name="Plan",
    full_name="syft.core.node.common.plan.Plan",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="actions",
            full_name="syft.core.node.common.plan.Plan.actions",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="inputs",
            full_name="syft.core.node.common.plan.Plan.inputs",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=148,
    serialized_end=253,
)

_PLAN.fields_by_name[
    "actions"
].message_type = proto_dot_core_dot_node_dot_common_dot_action_dot_action__pb2._ACTION
_PLAN.fields_by_name[
    "inputs"
].message_type = proto_dot_core_dot_pointer_dot_pointer__pb2._POINTER
DESCRIPTOR.message_types_by_name["Plan"] = _PLAN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Plan = _reflection.GeneratedProtocolMessageType(
    "Plan",
    (_message.Message,),
    {
        "DESCRIPTOR": _PLAN,
        "__module__": "proto.core.node.common.plan.plan_pb2"
        # @@protoc_insertion_point(class_scope:syft.core.node.common.plan.Plan)
    },
)
_sym_db.RegisterMessage(Plan)


# @@protoc_insertion_point(module_scope)
