# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/core/store/storable_object.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from syft.proto.core.common import uid_pb2 as proto_dot_core_dot_common_dot_uid__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/core/store/storable_object.proto',
  package='syft.core.store',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n&proto/core/store/storable_object.proto\x12\x0fsyft.core.store\x1a\x1bproto/core/common/uid.proto\"\xf6\x02\n\x0cStorableType\x12\x16\n\x0estorable_int32\x18\x01 \x01(\x05\x12\x16\n\x0estorable_int64\x18\x02 \x01(\x03\x12\x17\n\x0fstorable_string\x18\x03 \x01(\t\x12\x35\n\x0estorable_tuple\x18\x04 \x03(\x0b\x32\x1d.syft.core.store.StorableType\x12\x34\n\rstorable_list\x18\x05 \x03(\x0b\x32\x1d.syft.core.store.StorableType\x12\x43\n\x0cstorable_map\x18\x06 \x03(\x0b\x32-.syft.core.store.StorableType.StorableMapping\x1ak\n\x0fStorableMapping\x12*\n\x03key\x18\x01 \x01(\x0b\x32\x1d.syft.core.store.StorableType\x12,\n\x05value\x18\x02 \x01(\x0b\x32\x1d.syft.core.store.StorableType\"\x84\x01\n\x0eStorableObject\x12\"\n\x03key\x18\x01 \x01(\x0b\x32\x15.syft.core.common.UID\x12+\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x1d.syft.core.store.StorableType\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0c\n\x04tags\x18\x04 \x03(\tb\x06proto3'
  ,
  dependencies=[proto_dot_core_dot_common_dot_uid__pb2.DESCRIPTOR,])




_STORABLETYPE_STORABLEMAPPING = _descriptor.Descriptor(
  name='StorableMapping',
  full_name='syft.core.store.StorableType.StorableMapping',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='syft.core.store.StorableType.StorableMapping.key', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='syft.core.store.StorableType.StorableMapping.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=356,
  serialized_end=463,
)

_STORABLETYPE = _descriptor.Descriptor(
  name='StorableType',
  full_name='syft.core.store.StorableType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='storable_int32', full_name='syft.core.store.StorableType.storable_int32', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='storable_int64', full_name='syft.core.store.StorableType.storable_int64', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='storable_string', full_name='syft.core.store.StorableType.storable_string', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='storable_tuple', full_name='syft.core.store.StorableType.storable_tuple', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='storable_list', full_name='syft.core.store.StorableType.storable_list', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='storable_map', full_name='syft.core.store.StorableType.storable_map', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_STORABLETYPE_STORABLEMAPPING, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=463,
)


_STORABLEOBJECT = _descriptor.Descriptor(
  name='StorableObject',
  full_name='syft.core.store.StorableObject',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='syft.core.store.StorableObject.key', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='syft.core.store.StorableObject.data', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='syft.core.store.StorableObject.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tags', full_name='syft.core.store.StorableObject.tags', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=466,
  serialized_end=598,
)

_STORABLETYPE_STORABLEMAPPING.fields_by_name['key'].message_type = _STORABLETYPE
_STORABLETYPE_STORABLEMAPPING.fields_by_name['value'].message_type = _STORABLETYPE
_STORABLETYPE_STORABLEMAPPING.containing_type = _STORABLETYPE
_STORABLETYPE.fields_by_name['storable_tuple'].message_type = _STORABLETYPE
_STORABLETYPE.fields_by_name['storable_list'].message_type = _STORABLETYPE
_STORABLETYPE.fields_by_name['storable_map'].message_type = _STORABLETYPE_STORABLEMAPPING
_STORABLEOBJECT.fields_by_name['key'].message_type = proto_dot_core_dot_common_dot_uid__pb2._UID
_STORABLEOBJECT.fields_by_name['data'].message_type = _STORABLETYPE
DESCRIPTOR.message_types_by_name['StorableType'] = _STORABLETYPE
DESCRIPTOR.message_types_by_name['StorableObject'] = _STORABLEOBJECT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StorableType = _reflection.GeneratedProtocolMessageType('StorableType', (_message.Message,), {

  'StorableMapping' : _reflection.GeneratedProtocolMessageType('StorableMapping', (_message.Message,), {
    'DESCRIPTOR' : _STORABLETYPE_STORABLEMAPPING,
    '__module__' : 'proto.core.store.storable_object_pb2'
    # @@protoc_insertion_point(class_scope:syft.core.store.StorableType.StorableMapping)
    })
  ,
  'DESCRIPTOR' : _STORABLETYPE,
  '__module__' : 'proto.core.store.storable_object_pb2'
  # @@protoc_insertion_point(class_scope:syft.core.store.StorableType)
  })
_sym_db.RegisterMessage(StorableType)
_sym_db.RegisterMessage(StorableType.StorableMapping)

StorableObject = _reflection.GeneratedProtocolMessageType('StorableObject', (_message.Message,), {
  'DESCRIPTOR' : _STORABLEOBJECT,
  '__module__' : 'proto.core.store.storable_object_pb2'
  # @@protoc_insertion_point(class_scope:syft.core.store.StorableObject)
  })
_sym_db.RegisterMessage(StorableObject)


# @@protoc_insertion_point(module_scope)
