# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/lib/syfertext/data/readers/language_modeling/text_reader.proto

# third party
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


# syft absolute
from syft.proto.lib.syfertext.encoders import (
    sentence_encoder_pb2 as proto_dot_lib_dot_syfertext_dot_encoders_dot_sentence__encoder__pb2,
)

DESCRIPTOR = _descriptor.FileDescriptor(
    name="proto/lib/syfertext/data/readers/language_modeling/text_reader.proto",
    package="syft.lib.syfertext",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\nDproto/lib/syfertext/data/readers/language_modeling/text_reader.proto\x12\x12syft.lib.syfertext\x1a\x33proto/lib/syfertext/encoders/sentence_encoder.proto"^\n\nTextReader\x12\x0c\n\x04uuid\x18\x01 \x01(\x0c\x12\x0c\n\x04mode\x18\x02 \x01(\t\x12\x34\n\x07\x65ncoder\x18\x03 \x01(\x0b\x32#.syft.lib.syfertext.SentenceEncoderb\x06proto3',
    dependencies=[
        proto_dot_lib_dot_syfertext_dot_encoders_dot_sentence__encoder__pb2.DESCRIPTOR,
    ],
)


_TEXTREADER = _descriptor.Descriptor(
    name="TextReader",
    full_name="syft.lib.syfertext.TextReader",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="uuid",
            full_name="syft.lib.syfertext.TextReader.uuid",
            index=0,
            number=1,
            type=12,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"",
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="mode",
            full_name="syft.lib.syfertext.TextReader.mode",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="encoder",
            full_name="syft.lib.syfertext.TextReader.encoder",
            index=2,
            number=3,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=145,
    serialized_end=239,
)

_TEXTREADER.fields_by_name[
    "encoder"
].message_type = (
    proto_dot_lib_dot_syfertext_dot_encoders_dot_sentence__encoder__pb2._SENTENCEENCODER
)
DESCRIPTOR.message_types_by_name["TextReader"] = _TEXTREADER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TextReader = _reflection.GeneratedProtocolMessageType(
    "TextReader",
    (_message.Message,),
    {
        "DESCRIPTOR": _TEXTREADER,
        "__module__": "proto.lib.syfertext.data.readers.language_modeling.text_reader_pb2"
        # @@protoc_insertion_point(class_scope:syft.lib.syfertext.TextReader)
    },
)
_sym_db.RegisterMessage(TextReader)


# @@protoc_insertion_point(module_scope)
