# Starting from on the base image, copy the whole git repo and install
# PySyft in development mode, so that changes to its source are directly
# available when importing the module

FROM pysyft-base:local

RUN apk update
RUN apk add --no-cache \
  git redis

WORKDIR /usr/bin/
RUN git clone https://github.com/OpenMined/Capsule.git
WORKDIR /usr/bin/Capsule/
RUN pip3 install -r requirements.txt
RUN python3 setup.py install
RUN chmod +x build_and_run.sh build_and_run_django.sh build_and_run_zmq.sh

WORKDIR /PySyft
COPY . ./
RUN make develop
