# Starting from on the base image, copy the whole git repo and install
# PySyft in development mode, so that changes to its source are directly
# available when importing the module

FROM pysyft-base:local

WORKDIR /PySyft
COPY . ./
RUN make develop
