FROM bcgovimages/aries-cloudagent:py36-1.15-0_0.5.6

ADD configuration ./configuration
ADD scripts ./scripts

USER root

ADD https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 ./jq
RUN chmod +x ./jq

RUN chmod +x ./scripts/startup.sh
RUN chmod +x ./scripts/ngrok-wait.sh

USER $user

ENTRYPOINT  ["/usr/bin/env"]
CMD ./scripts/ngrok-wait.sh ./scripts/startup.sh