# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/lib/syfertext/data/units/attribute_values.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="proto/lib/syfertext/data/units/attribute_values.proto",
    package="syft.lib.syfertext",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n5proto/lib/syfertext/data/units/attribute_values.proto\x12\x12syft.lib.syfertext"*\n\x0f\x41ttributeValues\x12\x17\n\x0f\x61ttribute_value\x18\x01 \x03(\tb\x06proto3',
)


_ATTRIBUTEVALUES = _descriptor.Descriptor(
    name="AttributeValues",
    full_name="syft.lib.syfertext.AttributeValues",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="attribute_value",
            full_name="syft.lib.syfertext.AttributeValues.attribute_value",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=77,
    serialized_end=119,
)

DESCRIPTOR.message_types_by_name["AttributeValues"] = _ATTRIBUTEVALUES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AttributeValues = _reflection.GeneratedProtocolMessageType(
    "AttributeValues",
    (_message.Message,),
    {
        "DESCRIPTOR": _ATTRIBUTEVALUES,
        "__module__": "proto.lib.syfertext.data.units.attribute_values_pb2"
        # @@protoc_insertion_point(class_scope:syft.lib.syfertext.AttributeValues)
    },
)
_sym_db.RegisterMessage(AttributeValues)


# @@protoc_insertion_point(module_scope)
