# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/core/store/store_object.proto
"""Generated protocol buffer code."""
# third party
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


# third party
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2

# syft absolute
from syft.proto.core.common import (
    common_object_pb2 as proto_dot_core_dot_common_dot_common__object__pb2,
)

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n#proto/core/store/store_object.proto\x12\x0fsyft.core.store\x1a%proto/core/common/common_object.proto\x1a\x19google/protobuf/any.proto"\x82\x01\n\x12StoreGenericObject\x12\x38\n\x0fstorable_object\x18\x01 \x01(\x0b\x32\x1f.syft.core.store.StorableObject\x12\x32\n\x0cstore_object\x18\x02 \x01(\x0b\x32\x1c.syft.core.store.StoreObject"\xfa\x01\n\x0eStorableObject\x12!\n\x02id\x18\x01 \x01(\x0b\x32\x15.syft.core.common.UID\x12\x11\n\tdata_type\x18\x02 \x01(\t\x12\x1a\n\x12schematic_qualname\x18\x03 \x01(\t\x12"\n\x04\x64\x61ta\x18\x04 \x01(\x0b\x32\x14.google.protobuf.Any\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12\x0c\n\x04tags\x18\x06 \x03(\t\x12\x18\n\x10read_permissions\x18\x07 \x01(\x0c\x12\x1a\n\x12search_permissions\x18\x08 \x01(\x0c\x12\x19\n\x11write_permissions\x18\t \x01(\x0c"r\n\x0bStoreObject\x12-\n\tcontainer\x18\x01 \x01(\x0b\x32\x1a.syft.core.store.Container\x12\x34\n\rsearch_engine\x18\x02 \x01(\x0b\x32\x1d.syft.core.store.SearchEngine"\xb1\x01\n\tContainer\x12\x36\n\x0e\x64ict_container\x18\x01 \x01(\x0b\x32\x1e.syft.core.store.DictContainer\x12\x34\n\rsql_container\x18\x02 \x01(\x0b\x32\x1d.syft.core.store.SqlContainer\x12\x36\n\x0egrid_container\x18\x03 \x01(\x0b\x32\x1e.syft.core.store.GridContainer"\x0e\n\x0cSearchEngine"\xa0\x01\n\rDictContainer\x12\x45\n\x0c\x64ict_mapping\x18\x01 \x03(\x0b\x32/.syft.core.store.DictContainer.DictMappingEntry\x1aH\n\x10\x44ictMappingEntry\x12\x0b\n\x03key\x18\x01 \x01(\x03\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any:\x02\x38\x01"\x0e\n\x0cSqlContainer"\x0f\n\rGridContainerb\x06proto3'
)


_STOREGENERICOBJECT = DESCRIPTOR.message_types_by_name["StoreGenericObject"]
_STORABLEOBJECT = DESCRIPTOR.message_types_by_name["StorableObject"]
_STOREOBJECT = DESCRIPTOR.message_types_by_name["StoreObject"]
_CONTAINER = DESCRIPTOR.message_types_by_name["Container"]
_SEARCHENGINE = DESCRIPTOR.message_types_by_name["SearchEngine"]
_DICTCONTAINER = DESCRIPTOR.message_types_by_name["DictContainer"]
_DICTCONTAINER_DICTMAPPINGENTRY = _DICTCONTAINER.nested_types_by_name[
    "DictMappingEntry"
]
_SQLCONTAINER = DESCRIPTOR.message_types_by_name["SqlContainer"]
_GRIDCONTAINER = DESCRIPTOR.message_types_by_name["GridContainer"]
StoreGenericObject = _reflection.GeneratedProtocolMessageType(
    "StoreGenericObject",
    (_message.Message,),
    {
        "DESCRIPTOR": _STOREGENERICOBJECT,
        "__module__": "proto.core.store.store_object_pb2"
        # @@protoc_insertion_point(class_scope:syft.core.store.StoreGenericObject)
    },
)
_sym_db.RegisterMessage(StoreGenericObject)

StorableObject = _reflection.GeneratedProtocolMessageType(
    "StorableObject",
    (_message.Message,),
    {
        "DESCRIPTOR": _STORABLEOBJECT,
        "__module__": "proto.core.store.store_object_pb2"
        # @@protoc_insertion_point(class_scope:syft.core.store.StorableObject)
    },
)
_sym_db.RegisterMessage(StorableObject)

StoreObject = _reflection.GeneratedProtocolMessageType(
    "StoreObject",
    (_message.Message,),
    {
        "DESCRIPTOR": _STOREOBJECT,
        "__module__": "proto.core.store.store_object_pb2"
        # @@protoc_insertion_point(class_scope:syft.core.store.StoreObject)
    },
)
_sym_db.RegisterMessage(StoreObject)

Container = _reflection.GeneratedProtocolMessageType(
    "Container",
    (_message.Message,),
    {
        "DESCRIPTOR": _CONTAINER,
        "__module__": "proto.core.store.store_object_pb2"
        # @@protoc_insertion_point(class_scope:syft.core.store.Container)
    },
)
_sym_db.RegisterMessage(Container)

SearchEngine = _reflection.GeneratedProtocolMessageType(
    "SearchEngine",
    (_message.Message,),
    {
        "DESCRIPTOR": _SEARCHENGINE,
        "__module__": "proto.core.store.store_object_pb2"
        # @@protoc_insertion_point(class_scope:syft.core.store.SearchEngine)
    },
)
_sym_db.RegisterMessage(SearchEngine)

DictContainer = _reflection.GeneratedProtocolMessageType(
    "DictContainer",
    (_message.Message,),
    {
        "DictMappingEntry": _reflection.GeneratedProtocolMessageType(
            "DictMappingEntry",
            (_message.Message,),
            {
                "DESCRIPTOR": _DICTCONTAINER_DICTMAPPINGENTRY,
                "__module__": "proto.core.store.store_object_pb2"
                # @@protoc_insertion_point(class_scope:syft.core.store.DictContainer.DictMappingEntry)
            },
        ),
        "DESCRIPTOR": _DICTCONTAINER,
        "__module__": "proto.core.store.store_object_pb2"
        # @@protoc_insertion_point(class_scope:syft.core.store.DictContainer)
    },
)
_sym_db.RegisterMessage(DictContainer)
_sym_db.RegisterMessage(DictContainer.DictMappingEntry)

SqlContainer = _reflection.GeneratedProtocolMessageType(
    "SqlContainer",
    (_message.Message,),
    {
        "DESCRIPTOR": _SQLCONTAINER,
        "__module__": "proto.core.store.store_object_pb2"
        # @@protoc_insertion_point(class_scope:syft.core.store.SqlContainer)
    },
)
_sym_db.RegisterMessage(SqlContainer)

GridContainer = _reflection.GeneratedProtocolMessageType(
    "GridContainer",
    (_message.Message,),
    {
        "DESCRIPTOR": _GRIDCONTAINER,
        "__module__": "proto.core.store.store_object_pb2"
        # @@protoc_insertion_point(class_scope:syft.core.store.GridContainer)
    },
)
_sym_db.RegisterMessage(GridContainer)

if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _DICTCONTAINER_DICTMAPPINGENTRY._options = None
    _DICTCONTAINER_DICTMAPPINGENTRY._serialized_options = b"8\001"
    _STOREGENERICOBJECT._serialized_start = 123
    _STOREGENERICOBJECT._serialized_end = 253
    _STORABLEOBJECT._serialized_start = 256
    _STORABLEOBJECT._serialized_end = 506
    _STOREOBJECT._serialized_start = 508
    _STOREOBJECT._serialized_end = 622
    _CONTAINER._serialized_start = 625
    _CONTAINER._serialized_end = 802
    _SEARCHENGINE._serialized_start = 804
    _SEARCHENGINE._serialized_end = 818
    _DICTCONTAINER._serialized_start = 821
    _DICTCONTAINER._serialized_end = 981
    _DICTCONTAINER_DICTMAPPINGENTRY._serialized_start = 909
    _DICTCONTAINER_DICTMAPPINGENTRY._serialized_end = 981
    _SQLCONTAINER._serialized_start = 983
    _SQLCONTAINER._serialized_end = 997
    _GRIDCONTAINER._serialized_start = 999
    _GRIDCONTAINER._serialized_end = 1014
# @@protoc_insertion_point(module_scope)
