"""Reading every released syft-client serialized format with the current code.

Each fixture directory under fixtures/ is named ``syft_client-<version>-protocol<p>``
and holds the serialized artifacts exactly as that release produced them: the
published SYFT_version.json, one msgv2 proposed-changes blob and one events blob.
The current code must still read, upgrade and round-trip all of them.

Protocol 0 is the last release (0.1.117) without canonical_name/version identity
fields; protocol >= 1 writes them. Fixtures are generated by
scripts/generate_release_fixture.py (protocol 0 / 0.1.117 predates it and is
hand-authored).
"""

import json
import re
from pathlib import Path

import pytest

from syft_client.migrations import client_registry
from syft_client.sync.events.file_change_event import FileChangeEventsMessage
from syft_client.sync.messages.proposed_filechange import ProposedFileChangesMessage
from syft_client.sync.utils.syftbox_utils import uncompress_data
from syft_client.sync.version.version_info import VersionInfo

FIXTURES_DIR = Path(__file__).parent / "fixtures"
RELEASE_FIXTURES = sorted(FIXTURES_DIR.glob("syft_client-*-protocol*"))

released_fixtures = pytest.mark.parametrize(
    "fixture", RELEASE_FIXTURES, ids=lambda f: f.name
)


def _protocol_of(fixture: Path) -> str:
    return re.search(r"-protocol(\d+)$", fixture.name).group(1)


def _has_identity(protocol: str) -> bool:
    """canonical_name/version are written only from protocol 1 onwards."""
    return protocol != "0"


def _single(fixture: Path, pattern: str) -> Path:
    matches = list(fixture.glob(pattern))
    assert len(matches) == 1, f"expected one {pattern} in {fixture.name}"
    return matches[0]


def test_fixtures_exist():
    assert RELEASE_FIXTURES, "no release fixtures found"


@released_fixtures
def test_version_file_reads_and_round_trips(fixture: Path):
    raw = _single(fixture, "SYFT_version.json").read_text()
    assert ("canonical_name" in json.loads(raw)) == _has_identity(_protocol_of(fixture))

    info = VersionInfo.from_json(raw)
    assert info.version == client_registry.latest_version("VersionInfo")
    assert info.syft_client_version
    # Round-trip: what the current code writes must load again.
    assert VersionInfo.from_json(info.to_json()) == info


@released_fixtures
def test_proposed_message_reads_and_round_trips(fixture: Path):
    blob = _single(fixture, "msgv2_*.tar.gz").read_bytes()
    assert ("canonical_name" in json.loads(uncompress_data(blob))) == _has_identity(
        _protocol_of(fixture)
    )

    message = ProposedFileChangesMessage.from_compressed_data(blob)
    assert message.version == client_registry.latest_version(
        "ProposedFileChangesMessage"
    )
    changes = {c.path_in_datasite.name: c for c in message.proposed_file_changes}
    assert changes["notes.txt"].content == "hello from the release fixture"
    assert changes["blob.bin"].content == b"\x00\x01\x02fixture-binary"
    deletion = changes["removed.txt"]
    assert deletion.is_deleted and deletion.content is None
    assert deletion.new_hash is None and deletion.content_type is None

    # Upgrade-on-write: what the current code re-emits carries identity fields.
    rewritten = message.as_compressed_data()
    assert b'"canonical_name"' in uncompress_data(rewritten)
    restored = ProposedFileChangesMessage.from_compressed_data(rewritten)
    assert restored.proposed_file_changes == message.proposed_file_changes


@released_fixtures
def test_events_message_reads_and_round_trips(fixture: Path):
    blob = _single(fixture, "syfteventsmessagev3_*.tar.gz").read_bytes()
    assert ("canonical_name" in json.loads(uncompress_data(blob))) == _has_identity(
        _protocol_of(fixture)
    )

    message = FileChangeEventsMessage.from_compressed_data(blob)
    assert message.version == client_registry.latest_version("FileChangeEventsMessage")
    events = {e.path_in_datasite.name: e for e in message.events}
    assert events["notes.txt"].content == "hello from the release fixture"
    assert events["blob.bin"].content == b"\x00\x01\x02fixture-binary"
    assert events["removed.txt"].is_deleted and events["removed.txt"].content is None

    # Upgrade-on-write: what the current code re-emits carries identity fields.
    rewritten = message.as_compressed_data()
    assert b'"canonical_name"' in uncompress_data(rewritten)
    restored = FileChangeEventsMessage.from_compressed_data(rewritten)
    assert restored.events == message.events


@released_fixtures
def test_fixture_protocol_is_in_registry_history(fixture: Path):
    """Every fixture's protocol is either the current one or a released one
    the registry knows the schema for (so downgrades can target it)."""
    protocol = _protocol_of(fixture)
    schema = client_registry.schema_for_protocol_version(protocol)
    assert set(schema.supported_versions) == {
        "VersionInfo",
        "ProposedFileChangesMessage",
        "FileChangeEventsMessage",
    }
