"""Reading/writing jobs against every released syft-job on-disk layout.

Each fixture tree under fixtures/ is named ``syft_job-<version>-protocol<p>_syftbox``
and holds a SyftBox exactly as that release wrote jobs to disk: a ``scanned.job``
(with a review state.yaml) and an ``unscanned.job`` (inbox only). The current code
must still read, upgrade and round-trip all of them.

Protocol 0 is the last release (0.1.38) without a v<n> path segment or
canonical_name/version fields; protocol >= 1 stores jobs under a v<n> segment and
writes those identity fields. Fixtures are generated by
scripts/generate_release_fixture.py (protocol 0 / 0.1.38 predates it and is
hand-authored).
"""

import re
import shutil
from pathlib import Path

import pytest
import yaml
from syft_job.client import JobClient
from syft_job.config import SyftJobConfig, protocol_dir_name
from syft_job.migrations import job_registry
from syft_job.migrations.registry import JOB_PROTOCOL_VERSION
from syft_job.models import JobSubmissionMetadata
from syft_migration import MigrationService

DO_EMAIL = "do@test.org"
DS_EMAIL = "ds@test.org"
SCANNED = "scanned.job"
UNSCANNED = "unscanned.job"

FIXTURES_DIR = Path(__file__).parent / "fixtures"
RELEASE_FIXTURES = sorted(FIXTURES_DIR.glob("syft_job-*-protocol*_syftbox"))
PROTOCOLS = sorted(
    {re.search(r"-protocol(\d+)_syftbox$", f.name).group(1) for f in RELEASE_FIXTURES}
)

released_syftbox_fixtures = pytest.mark.parametrize(
    "fixture", RELEASE_FIXTURES, ids=lambda f: f.name
)


def _protocol_of(fixture: Path) -> str:
    return re.search(r"-protocol(\d+)_syftbox$", fixture.name).group(1)


def _has_identity(protocol: str) -> bool:
    """canonical_name/version are written only from protocol 1 onwards."""
    return protocol != "0"


def _syftbox_w_old_protocol_jobs(fixture: Path, tmp_path: Path) -> Path:
    """A syftbox seeded with the jobs a released protocol wrote to disk."""
    syftbox_w_old_protocol_jobs = tmp_path / "SyftBox"
    shutil.copytree(fixture, syftbox_w_old_protocol_jobs)
    return syftbox_w_old_protocol_jobs


def _do_client_current_protocol(syftbox: Path) -> JobClient:
    config = SyftJobConfig(syftbox_folder=syftbox, current_user_email=DO_EMAIL)
    return JobClient(config=config)


def _review_state_path(syftbox: Path, protocol: str, job_name: str) -> Path:
    seg = protocol_dir_name(protocol)  # None for "0", "v<p>" otherwise
    base = syftbox / DO_EMAIL / "app_data/job/review" / DS_EMAIL
    return (base / seg if seg else base) / job_name / "state.yaml"


def _expected_state_yaml(job, protocol: str) -> str:
    """The exact bytes the given protocol writes for this job's state."""
    state = job._state
    if protocol != JOB_PROTOCOL_VERSION:
        state = MigrationService(registry=job_registry).downgrade_for_protocol_version(
            state, protocol
        )
    data = state.model_dump(mode="json")
    if not _has_identity(protocol):
        data.pop("canonical_name")
        data.pop("version")
    return yaml.dump(data, default_flow_style=False)


@released_syftbox_fixtures
def test_release_jobs_load_and_upgrade(fixture: Path, tmp_path: Path):
    syftbox_w_old_protocol_jobs = _syftbox_w_old_protocol_jobs(fixture, tmp_path)
    do_client_current_protocol = _do_client_current_protocol(
        syftbox_w_old_protocol_jobs
    )

    old_protocol_jobs = do_client_current_protocol.jobs
    assert {job.name for job in old_protocol_jobs} == {SCANNED, UNSCANNED}
    latest_meta_version = job_registry.latest_version("JobSubmissionMetadata")
    latest_state_version = job_registry.latest_version("JobState")
    for old_protocol_job in old_protocol_jobs:
        # Every release's jobs load into the latest registered versions into memory
        assert isinstance(old_protocol_job.job_metadata, JobSubmissionMetadata)
        assert old_protocol_job.job_metadata.version == latest_meta_version
        assert old_protocol_job._state.version == latest_state_version

    scanned_old_protocol_job = next(j for j in old_protocol_jobs if j.name == SCANNED)
    assert scanned_old_protocol_job.submitted_by == DS_EMAIL
    assert scanned_old_protocol_job.job_metadata.datasite_email == DO_EMAIL
    assert scanned_old_protocol_job.status == "pending"


@released_syftbox_fixtures
def test_scan_inbox_writes_state_in_release_layout(fixture: Path, tmp_path: Path):
    protocol = _protocol_of(fixture)
    syftbox_w_old_protocol_jobs = _syftbox_w_old_protocol_jobs(fixture, tmp_path)

    do_client_current_protocol = _do_client_current_protocol(
        syftbox_w_old_protocol_jobs
    )
    do_client_current_protocol.scan_inbox()

    # State written next to the job in that release's layout and format.
    state_path = _review_state_path(syftbox_w_old_protocol_jobs, protocol, UNSCANNED)
    assert state_path.exists()
    raw = yaml.safe_load(state_path.read_text())
    assert ("canonical_name" in raw) is _has_identity(protocol)
    assert ("version" in raw) is _has_identity(protocol)
    assert raw["status"] == "pending"


@released_syftbox_fixtures
def test_approve_writes_back_release_format(fixture: Path, tmp_path: Path):
    protocol = _protocol_of(fixture)
    syftbox_w_old_protocol_jobs = _syftbox_w_old_protocol_jobs(fixture, tmp_path)
    do_client_current_protocol = _do_client_current_protocol(
        syftbox_w_old_protocol_jobs
    )

    scanned_old_protocol_job = next(
        j for j in do_client_current_protocol.jobs if j.name == SCANNED
    )
    scanned_old_protocol_job.approve(reason="ok")

    # Byte-exact output for that release, readable by a plain-yaml reader.
    state_path = _review_state_path(syftbox_w_old_protocol_jobs, protocol, SCANNED)
    assert state_path.read_text() == _expected_state_yaml(
        scanned_old_protocol_job, protocol
    )
    assert yaml.safe_load(state_path.read_text())["status"] == "approved"


@released_syftbox_fixtures
def test_mixed_protocol_listing(fixture: Path, tmp_path: Path):
    syftbox_w_old_protocol_jobs = _syftbox_w_old_protocol_jobs(fixture, tmp_path)
    ds_config_current_protocol = SyftJobConfig(
        syftbox_folder=syftbox_w_old_protocol_jobs, current_user_email=DS_EMAIL
    )
    ds_client_current_protocol = JobClient(config=ds_config_current_protocol)
    ds_client_current_protocol.submit_bash_job(
        user=DO_EMAIL, script="echo hi", job_name="new.job"
    )

    listed_jobs = _do_client_current_protocol(syftbox_w_old_protocol_jobs).jobs
    assert {job.name for job in listed_jobs} == {SCANNED, UNSCANNED, "new.job"}


@released_syftbox_fixtures
def test_job_reprs_do_not_error(fixture: Path, tmp_path: Path):
    syftbox_w_old_protocol_jobs = _syftbox_w_old_protocol_jobs(fixture, tmp_path)
    old_protocol_jobs = _do_client_current_protocol(syftbox_w_old_protocol_jobs).jobs

    # The job-list and single-job displays all render without error.
    for render in (repr, str, lambda o: o._repr_html_()):
        assert render(old_protocol_jobs)
        assert render(old_protocol_jobs[0])


@pytest.mark.parametrize("protocol", PROTOCOLS)
def test_submit_to_peer_writes_that_protocol_layout(protocol: str, tmp_path: Path):
    syftbox = tmp_path / "SyftBox"
    syftbox.mkdir()
    ds_config_current_protocol = SyftJobConfig(
        syftbox_folder=syftbox, current_user_email=DS_EMAIL
    )
    peer_schema = job_registry.schema_for_protocol_version(protocol)
    ds_client_current_protocol = JobClient(
        config=ds_config_current_protocol, peer_schemas={DO_EMAIL: peer_schema}
    )

    job_dir = ds_client_current_protocol.submit_bash_job(
        user=DO_EMAIL, script="echo hi", job_name="peer.job"
    )

    # Layout and format match the peer's protocol.
    assert job_dir.parent.name == (protocol_dir_name(protocol) or DS_EMAIL)
    raw = yaml.safe_load((job_dir / "config.yaml").read_text())
    assert ("canonical_name" in raw) is _has_identity(protocol)
    assert ("version" in raw) is _has_identity(protocol)
    # The DS's own (current) client still lists and reads it back.
    assert ds_client_current_protocol.jobs[0].name == "peer.job"
