# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/lib/pandas/frame.proto
"""Generated protocol buffer code."""
# third party
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1cproto/lib/pandas/frame.proto\x12\x0fsyft.lib.pandas"?\n\x0fPandasDataFrame\x12\x11\n\tdataframe\x18\x01 \x01(\x0c\x12\x19\n\x11\x64\x65\x63ompressed_size\x18\x02 \x01(\x04\x62\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "proto.lib.pandas.frame_pb2", globals()
)
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _PANDASDATAFRAME._serialized_start = 49
    _PANDASDATAFRAME._serialized_end = 112
# @@protoc_insertion_point(module_scope)
