# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/syft_object.proto
"""Generated protocol buffer code."""
# third party
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


# syft absolute
from syft.proto.ast import ast_object_pb2 as proto_dot_ast_dot_ast__object__pb2
from syft.proto.core import core_object_pb2 as proto_dot_core_dot_core__object__pb2
from syft.proto.lib import lib_object_pb2 as proto_dot_lib_dot_lib__object__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
    name="proto/syft_object.proto",
    package="syft",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b"\n\x17proto/syft_object.proto\x12\x04syft\x1a\x1cproto/core/core_object.proto\x1a\x1aproto/ast/ast_object.proto\x1a\x1aproto/lib/lib_object.proto\"\x81\x01\n\nSyftObject\x12'\n\x08\x63ore_obj\x18\x01 \x01(\x0b\x32\x15.syft.core.CoreObject\x12$\n\x07\x61st_obj\x18\x02 \x01(\x0b\x32\x13.syft.ast.AstObject\x12$\n\x07lib_obj\x18\x03 \x01(\x0b\x32\x13.syft.lib.LibObjectb\x06proto3",
    dependencies=[
        proto_dot_core_dot_core__object__pb2.DESCRIPTOR,
        proto_dot_ast_dot_ast__object__pb2.DESCRIPTOR,
        proto_dot_lib_dot_lib__object__pb2.DESCRIPTOR,
    ],
)


_SYFTOBJECT = _descriptor.Descriptor(
    name="SyftObject",
    full_name="syft.SyftObject",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="core_obj",
            full_name="syft.SyftObject.core_obj",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="ast_obj",
            full_name="syft.SyftObject.ast_obj",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="lib_obj",
            full_name="syft.SyftObject.lib_obj",
            index=2,
            number=3,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=120,
    serialized_end=249,
)

_SYFTOBJECT.fields_by_name[
    "core_obj"
].message_type = proto_dot_core_dot_core__object__pb2._COREOBJECT
_SYFTOBJECT.fields_by_name[
    "ast_obj"
].message_type = proto_dot_ast_dot_ast__object__pb2._ASTOBJECT
_SYFTOBJECT.fields_by_name[
    "lib_obj"
].message_type = proto_dot_lib_dot_lib__object__pb2._LIBOBJECT
DESCRIPTOR.message_types_by_name["SyftObject"] = _SYFTOBJECT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SyftObject = _reflection.GeneratedProtocolMessageType(
    "SyftObject",
    (_message.Message,),
    {
        "DESCRIPTOR": _SYFTOBJECT,
        "__module__": "proto.syft_object_pb2"
        # @@protoc_insertion_point(class_scope:syft.SyftObject)
    },
)
_sym_db.RegisterMessage(SyftObject)


# @@protoc_insertion_point(module_scope)
